apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    k8s-app: heapster
    name: heapster
    version: v6
  name: heapster
  namespace: kube-system
spec:
  replicas: 1
  selector:
    k8s-app: heapster
    version: v6
  template:
    metadata:
      labels:
        k8s-app: heapster
        version: v6
    spec:
      containers:
      - name: heapster
        image: ##DOCKER_REGISTRY##/kubernetes/heapster
        imagePullPolicy: Always
        command:
        - /heapster
        - --source=kubernetes:http://##HOST_IP##:8080
        - --sink=influxdb:http://##INFLUXDB_IP##:8086
        - --vmodule=*=4
#        env:
#        - name: KUBERNETES_SERVICE_HOST
#          value: serverfeab644b-8266-46fb-a287-7d3822329683
